name: control-center-images
lang: python
lang_version: 2.7
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp-dockerfile
  docker_repos: ["confluentinc/cp-enterprise-control-center",]
  maven_phase: 'package'
  maven_skip_deploy: true
  build_arm: true
  os_types: ["ubi8"]
  nano_version: true
  use_packages: true
  cp_images: true